### ISSUE TITLE
Always fails with "undefined symbol: dgesv_" on Ubuntu 20.04 and Python 3.8

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/SurfaceTopography#209]
# Issue

The singularity file says `singularity/SurfaceTopography_serial.def` "Ubuntu 20 funktioniert nicht". Would still like to run on it on 20.04. Tried the following and other variations of what's described on https://contactengineering.github.io/SurfaceTopography/installation.html#updating-surfacetopography and in the singularity file without success. 

# Setup

Condensed:

from within `ContactEngineering/SurfaceTopography` cloned repo root,

```bash

cd test/file_format_examples

# sample code from https://contactengineering.github.io/SurfaceTopography/usage.html
cat << EOF > sample.py
from SurfaceTopography import open_topography

# get a handle to the file ("reader")
reader = open_topography("example.opd")   # you can find this file in the folder 'tests/file_format_examples'

# each file has a list of channels (one or more)
print(reader.channels)  # returns list of channels
ch = reader.channel[0]  # first channel, alternatively use ..
ch = reader.default_channel  # .. - one of the channels is the "default" channel

# each channel has some defined meta data
print(ch.name)  # channel name
print(ch.physical_sizes)  # lateral dimensions
print(ch.nb_grid_pts)  # number of grid points
print(ch.dim)  # number of dimensions (1 or 2)
print(ch.info)  # more metadata, e.g. 'unit' if unit was given in file

# you can get a topography from a channel
topo = ch.topography()   # here meta data from the file is taken
topo = ch.topography(physical_sizes=(20,30))   # like this, you can overwrite meta data in file

# each topography has a rich set of methods and properties for meta data and analysis
print(topo.physical_sizes)  # lateral dimension
print(topo.rms_height_from_area())  # Root mean square of heights
EOF

cd ../..

# as in singularity/SurfaceTopography_serial.def
sudo apt install clang cmake curl wget g++ git libboost-test-dev libcurl4-openssl-dev libeigen3-dev libfftw3-dev libgmp-dev libnetcdf-dev libopenblas-dev m4 python3-pip python3-dev python3-netcdf4 gdb git

# with or without exports (what's actually in the singularity definition file that would end up below /usr/local?)
export PATH=/usr/local/bin:$PATH
export LD_RUN_PATH=/usr/local/lib:$LD_RUN_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export MANPATH=/usr/local/share/man:$MANPATH

python3 -m venv ~/venv/contact.engineering-python-3.8
source ~/venv/contact.engineering-python-3.8/bin/activate
pip install --upgrade pip

# with or without --no-binary numpy (added on Lars' recommendation)
pip install -r requirements.txt --no-binary numpy
# with or without -e
pip install -e .

cd test/file_format_examples/
python sample.py
```

leads to

# Failure

```console
$ python sample.py 
Traceback (most recent call last):
  File "sample.py", line 1, in <module>
    from SurfaceTopography import open_topography
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/__init__.py", line 31, in <module>
    from .Container import SurfaceContainer, read_container, read_published_container  # noqa: F401
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/Container/__init__.py", line 27, in <module>
    from .IO import read_container, read_published_container  # noqa: F401
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/Container/IO.py", line 43, in <module>
    from ..IO import open_topography
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/IO/__init__.py", line 34, in <module>
    from .FromFile import HGTReader, X3PReader
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/IO/FromFile.py", line 39, in <module>
    from ..UniformLineScanAndTopography import Topography
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/UniformLineScanAndTopography.py", line 36, in <module>
    from .HeightContainer import (
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py", line 38, in <module>
    from .Support import doi, DeprecatedDictionary
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/Support/__init__.py", line 28, in <module>
    from .Interpolation import Bicubic  # noqa: F401
  File "/home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/SurfaceTopography/Support/Interpolation.py", line 30, in <module>
    from _SurfaceTopography import Bicubic  # noqa: F401
ImportError: /home/jotelha/venv/contact.engineering-python-3.8/lib/python3.8/site-packages/_SurfaceTopography.cpython-38-x86_64-linux-gnu.so: undefined symbol: dgesv_
```

Looks like it's related to https://contactengineering.github.io/SurfaceTopography/installation.html#installation-problems-with-lapack-and-openblas. Any other ideas? 

# environment

```console
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

$ python --version
Python 3.8.10

$ pip freeze
alabaster==0.7.12
astroid==2.11.6
attrs==21.4.0
Babel==2.10.3
certifi==2022.6.15
charset-normalizer==2.0.12
coverage==6.4.1
cycler==0.11.0
defusedxml==0.7.1
dill==0.3.5.1
docutils==0.18.1
flake8==4.0.1
fonttools==4.33.3
h5py==3.7.0
idna==3.3
igor==0.3
imagesize==1.3.0
importlib-metadata==4.11.4
iniconfig==1.1.1
isort==5.10.1
Jinja2==3.1.2
kiwisolver==1.4.3
lazy-object-proxy==1.7.1
MarkupSafe==2.1.1
matplotlib==3.5.2
mccabe==0.7.0
mpi4py==3.1.3
muFFT==0.23.1
NuMPI==0.3.0
numpy==1.21.6
numpyencoder==0.3.0
packaging==21.3
pep8==1.7.1
Pillow==9.1.1
platformdirs==2.5.2
pluggy==1.0.0
py==1.11.0
pycodestyle==2.8.0
pyflakes==2.4.0
Pygments==2.12.0
pylint==2.14.3
pyparsing==3.0.9
pytest==7.1.2
pytest-flake8==1.1.1
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
requests==2.28.0
runtests==0.0.28
scipy==1.8.1
setuptools-scm==6.4.2
six==1.16.0
snowballstemmer==2.2.0
Sphinx==5.0.2
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
-e git+git@github.com:ContactEngineering/SurfaceTopography.git@1bb8b2246b010668f08c05306f98dc74046a487a#egg=SurfaceTopography
tomli==2.0.1
tomlkit==0.11.0
typing-extensions==4.2.0
urllib3==1.26.9
wrapt==1.14.1
zipp==3.8.0

```

**Comment by pastewka** [comment]
I hate this @sannant I've seen this but don't remember how to resolve. Any ideas?

**Comment by pastewka** [comment]
I think this can only be a *-dev package that is missing. I've always had it running smoothly on Ubuntu.

**Comment by jotelha** [comment]
Got a bit further here, though I am not sure what exactly caused the above to fail earlier, and I am also not sure what exactly led to success now.

What I did differently now was this:

```
sudo apt-get install libopenblas-dev libopenblas-base
```

`libopenblas-dev` had been there before, but not `libopenblas-base`

Removed a `_SurfaceTopography.cpython-38-x86_64-linux-gnu.so ` build file that was left over in the root of the repository by some earlier attempt (I suspect the `pip install -e .`).

Only ran this from within root of repository,

```
python3 -m venv venv
source venv/bin/activate
pip install . --no-binary numpy
```
The build output looks like this,

```
$ pip install . --no-binary numpy
Processing /home/jotelha/git/ContactEngineering/SurfaceTopography
Processing /home/jotelha/.cache/pip/wheels/a0/37/91/2c57e1b7638be9d658fdd84a0bcd95ff99a6e158f07ae14165/NuMPI-0.3.0-py3-none-any.whl
Collecting Pillow
  Using cached Pillow-9.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting h5py
  Using cached h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
Processing /home/jotelha/.cache/pip/wheels/d4/05/ba/29dcb3ea3df026233ad7419141cbdea30f43ab9e4993589ebc/igor-0.3-py3-none-any.whl
Collecting matplotlib>=1.0.0
  Using cached matplotlib-3.5.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
Processing /home/jotelha/.cache/pip/wheels/c9/1d/8b/3fdfa4d0b82637236ec2d6ee76c58c9e3c0c455702b924099d/muFFT-0.23.1-cp38-cp38-linux_x86_64.whl
Collecting numpy>=1.16.3
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpyencoder
  Using cached numpyencoder-0.3.0-py3-none-any.whl (3.0 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting requests
  Using cached requests-2.28.0-py3-none-any.whl (62 kB)
Collecting scipy>=1.1.0
  Using cached scipy-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Processing /home/jotelha/.cache/pip/wheels/aa/c1/3d/9d4f406c1cefee8cefec7ac511a3147cd6cc39412b27bb5bc5/mpi4py-3.1.3-cp38-cp38-linux_x86_64.whl
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Building wheels for collected packages: SurfaceTopography, numpy
  Building wheel for SurfaceTopography (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jotelha/git/ContactEngineering/SurfaceTopography/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-tezni672/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-tezni672/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-c0dfpoec
       cwd: /tmp/pip-req-build-tezni672/
  Complete output (35 lines):
  WARNING: Could not find numpy, skipping LAPACK detection.
  []
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  WARNING: The wheel package is not available.
  /tmp/pip-req-build-tezni672/.eggs/setuptools_scm-6.4.2-py3.8.egg/setuptools_scm/integration.py:17: RuntimeWarning:
  ERROR: setuptools==44.0.0 is used in combination with setuptools_scm>=6.x
  
  Your build configuration is incomplete and previously worked by accident!
  
  
  This happens as setuptools is unable to replace itself when a activated build dependency
  requires a more recent setuptools version
  (it does not respect "setuptools>X" in setup_requires).
  
  
  setuptools>=31 is required for setup.cfg metadata support
  setuptools>=42 is required for pyproject.toml configuration support
  
  Suggested workarounds if applicable:
   - preinstalling build dependencies like setuptools_scm before running setup.py
   - installing setuptools_scm using the system package manager to ensure consistency
   - migrating from the deprecated setup_requires mechanism to pep517/518
     and using a pyproject.toml to declare build dependencies
     which are reliably pre-installed before running the build tools
  
    warnings.warn(
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for SurfaceTopography
  Running setup.py clean for SurfaceTopography
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.22.4-cp38-cp38-linux_x86_64.whl size=18979008 sha256=59fbb4b61d1705394507b9261f7e7abf9732c41cdaa1600c166bf43a1d6e0632
  Stored in directory: /home/jotelha/.cache/pip/wheels/c7/6c/43/ceeebf0411159c5857528fad0d636e0f380c017605f12c4b54
Successfully built numpy
Failed to build SurfaceTopography
Installing collected packages: numpy, scipy, NuMPI, Pillow, defusedxml, h5py, igor, cycler, kiwisolver, fonttools, six, python-dateutil, pyparsing, packaging, matplotlib, mpi4py, muFFT, numpyencoder, pyyaml, urllib3, idna, certifi, charset-normalizer, requests, SurfaceTopography
    Running setup.py install for SurfaceTopography ... done
Successfully installed NuMPI-0.3.0 Pillow-9.1.1 SurfaceTopography-1.1.dev2+g1bb8b224 certifi-2022.6.15 charset-normalizer-2.0.12 cycler-0.11.0 defusedxml-0.7.1 fonttools-4.33.3 h5py-3.7.0 idna-3.3 igor-0.3 kiwisolver-1.4.3 matplotlib-3.5.2 mpi4py-3.1.3 muFFT-0.23.1 numpy-1.22.4 numpyencoder-0.3.0 packaging-21.3 pyparsing-3.0.9 python-dateutil-2.8.2 pyyaml-6.0 requests-2.28.0 scipy-1.8.1 six-1.16.0 urllib3-1.26.9
```

and the resulting environment looks much smaller, without installing anything from `requirements.txt`,

```console
$ pip freeze
certifi==2022.6.15
charset-normalizer==2.0.12
cycler==0.11.0
defusedxml==0.7.1
fonttools==4.33.3
h5py==3.7.0
idna==3.3
igor==0.3
kiwisolver==1.4.3
matplotlib==3.5.2
mpi4py==3.1.3
muFFT==0.23.1
NuMPI==0.3.0
numpy==1.22.4
numpyencoder==0.3.0
packaging==21.3
Pillow==9.1.1
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
requests==2.28.0
scipy==1.8.1
six==1.16.0
SurfaceTopography==1.1.dev2+g1bb8b224
urllib3==1.26.9
```

Now, the `undefined symbol` error has disappeared, and instead I just get this

```
$ python sample.py 
[<SurfaceTopography.IO.Reader.ChannelInfo object at 0x7fc1bf8d6eb0>]
Traceback (most recent call last):
  File "sample.py", line 8, in <module>
    ch = reader.channel[0]  # first channel, alternatively use ..
AttributeError: 'OPDReader' object has no attribute 'channel'
``` 

but that I get as well when building and running the singularity image from `singularity/SurfaceTopography_serial.def` on the sample script, so that's another issue. The tests are running through (1239 passed, 19 skipped, 133 warnings in 288.71s (0:04:48))

**Comment by pastewka** [comment]
This is ˋreader.channelsˋ. Looks like a bug in the example. We should run the examples im CI.

**Comment by jotelha** [comment]
Opened another ticket for that, https://github.com/ContactEngineering/SurfaceTopography/issues/210
