### ISSUE TITLE
Installation broken with v1.2.5

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/SurfaceTopography#264]
Installing `SurfaceTopography` with `pip install --no-binary numpy SurfaceTopography` fails for v1.2.5 with

```
 #12 1.082   Downloading surfacetopography-1.2.5.tar.gz (7.5 MB)
#12 1.396      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 24.3 MB/s eta 0:00:00
#12 1.943   Installing build dependencies: started
#12 71.20   Installing build dependencies: still running...
#12 148.8   Installing build dependencies: still running...
#12 210.1   Installing build dependencies: still running...
#12 268.8   Installing build dependencies: finished with status 'done'
#12 268.8   Getting requirements to build wheel: started
#12 268.9   Getting requirements to build wheel: finished with status 'done'
#12 269.1   Installing backend dependencies: started
#12 271.3   Installing backend dependencies: finished with status 'done'
#12 271.3   Preparing metadata (pyproject.toml): started
#12 271.4   Preparing metadata (pyproject.toml): finished with status 'error'
#12 271.4   error: subprocess-exited-with-error
#12 271.4   
#12 271.4   × Preparing metadata (pyproject.toml) did not run successfully.
#12 271.4   │ exit code: 1
#12 271.4   ╰─> [42 lines of output]
#12 271.4       + meson setup --prefix=/usr /tmp/pip-install-p3iyxxqq/surfacetopography_65c56cfa4932408f82ec598bedcb7ce4 /tmp/pip-install-p3iyxxqq/surfacetopography_65c56cfa4932408f82ec598bedcb7ce4/.mesonpy-lswosn4j/build --native-file=/tmp/pip-install-p3iyxxqq/surfacetopography_65c56cfa4932408f82ec598bedcb7ce4/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
#12 271.4       Traceback (most recent call last):
#12 271.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
#12 271.4           hook = backend.prepare_metadata_for_build_wheel
#12 271.4       AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
#12 271.4       
#12 271.4       During handling of the above exception, another exception occurred:
#12 271.4       
#12 271.4       Traceback (most recent call last):
#12 271.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#12 271.4           main()
#12 271.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#12 271.4           json_out['return_val'] = hook(**hook_input['kwargs'])
#12 271.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
#12 271.4           whl_basename = backend.build_wheel(metadata_directory, config_settings)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 1060, in build_wheel
#12 271.4           with _project(config_settings) as project:
#12 271.4         File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
#12 271.4           return next(self.gen)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 975, in _project
#12 271.4           with Project.with_temp_working_dir(
#12 271.4         File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
#12 271.4           return next(self.gen)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
#12 271.4           yield cls(source_dir, tmpdir, build_dir, meson_args)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 632, in __init__
#12 271.4           self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 680, in _configure
#12 271.4           self._meson('setup', *setup_args)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 657, in _meson
#12 271.4           return self._proc('meson', *args)
#12 271.4         File "/tmp/pip-build-env-3lm2ktrc/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 652, in _proc
#12 271.4           subprocess.check_call(list(args), env=self._env)
#12 271.4         File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
#12 271.4           retcode = call(*popenargs, **kwargs)
#12 271.4         File "/usr/lib/python3.10/subprocess.py", line 345, in call
#12 271.4           with Popen(*popenargs, **kwargs) as p:
#12 271.4         File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
#12 271.4           self._execute_child(args, executable, preexec_fn, close_fds,
#12 271.4         File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
#12 271.4           raise child_exception_type(errno_num, err_msg, err_filename)
#12 271.4       FileNotFoundError: [Errno 2] No such file or directory: 'meson'
#12 271.4       [end of output]
```

This happened within the automatic container build workflow at https://github.com/ContactEngineering/ce-container-stack/actions

**Comment by pastewka** [comment]
It should automatically install those. On Ubuntu also: `apt install meson ninja-build`

**Comment by pastewka** [comment]
It should automatically install those. On Ubuntu also: `apt install meson ninja-build`

**Comment by pastewka** [comment]
I've seen both cases: It works of the box and it complains about missing meson.

Could it be that it does not work if pip is too old? Can you try `pip install --upgrade pip` before installing `SurfaceTopography`?

**Comment by jotelha** [comment]
Tried that now in https://github.com/ContactEngineering/ce-container-stack/pull/1, i.e. 

```bash
pip install --upgrade pip && \
pip install SurfaceTopography
```

but that leads back to the initial error of

```
FileNotFoundError: [Errno 2] No such file or directory: 'meson'
```
Doesn't pull meson automatically, but it's fine for now, no need to look into this any further until it comes up again.
