### ISSUE TITLE
Error When Opening DATX Files: Unpacking Values Issue

### ISSUE THREAD

**Issue by nombac** [ContactEngineering/SurfaceTopography#367]
## Description
When attempting to open `.datx` files (e.g. [test.datx](https://www.dropbox.com/scl/fi/zbhvolt2rip5qs4bbqiaf/test.datx?rlkey=u4k6wn4ybaaxuoulw423rpqzm&dl=0)) using the `open_topography` function, an error occurs related to unpacking values. This issue prevents successful file operations on `.datx` format data.

## Error Message
The following traceback details the specific error encountered:
```
Traceback (most recent call last):
  File "/Users/shirose/Library/CloudStorage/Dropbox/test.py", line 11, in <module>
    reader = open_topography(filename, format='datx')
  File "/Users/shirose/Library/Python/3.12/lib/python/site-packages/SurfaceTopography/IO/__init__.py", line 240, in open_topography
    return lookup_reader_by_format[format](fobj, **kwargs)
  File "/Users/shirose/Library/Python/3.12/lib/python/site-packages/SurfaceTopography/IO/DATX.py", line 101, in __init__
    category, unit, values = x_converter
ValueError: too many values to unpack (expected 3)
```

**Comment by nombac** [comment]
I'm not an expert in DATX format or HDF5 technology. However, I wanted to share a Python code snippet, adapted by ChatGPT from a MATLAB sample provided by Zygo, that appears to successfully read DATX files. I hope this can help address the issue reported above.

```
import h5py
import numpy as np
import matplotlib.pyplot as plt

def read_datx(file_name):
    """Read .datx file and extract Surface data for visualization."""
    with h5py.File(file_name, 'r') as file:
        if 'Data/Surface' in file:
            surface_keys = list(file['Data/Surface'].keys())
            if surface_keys:
                surface_data_key = surface_keys[0]
                surface_data = file[f'Data/Surface/{surface_data_key}'][:]
                
                print("Data statistics:")
                print("Min:", np.min(surface_data))
                print("Max:", np.max(surface_data))
                print("Mean:", np.mean(surface_data))
                print("Standard Deviation:", np.std(surface_data))
                
                # Detecting the location of the extremely high values
                extreme_value_threshold = 1e+308  # Adjust the threshold appropriately
                extreme_indices = np.where(surface_data >= extreme_value_threshold)
                print("Locations of extreme values:", extreme_indices)
                
                # Normalize or clip extreme values for visualization:
                clipped_data = np.clip(surface_data, np.percentile(surface_data, 1), np.percentile(surface_data, 99))
                
                plt.imshow(clipped_data, cmap='viridis', interpolation='nearest')
                plt.colorbar()
                plt.scatter(extreme_indices[1], extreme_indices[0], color='red', s=50, label='Extreme Values')  # Red dots
                plt.legend()
                plt.title('Surface Data Visualization with Extreme Values Highlighted')
                plt.show()
        else:
            print("No Surface data available.")

read_datx('./test.datx')
```

**Comment by pastewka** [comment]
@nombac - I am sorry that just now I am looking at this. Would you mind sharing the offending file (and can I add it to the automated testing framework). This will help me fix this. I'll do this asap.

**Comment by pastewka** [comment]
I am sorry, I see that you actually shared that file
